
import React from 'react'
import html2pdf from 'html2pdf.js'

export default function PDFExport({ data, title = "Financial Calculator Results" }) {
  const exportToPDF = () => {
    const element = document.createElement('div')
    element.innerHTML = generatePDFContent()
    
    const opt = {
      margin: 0.5,
      filename: `financial-calculator-${Date.now()}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    }

    html2pdf().set(opt).from(element).save()
  }

  const generatePDFContent = () => {
    const currentDate = new Date().toLocaleDateString()
    const currentTime = new Date().toLocaleTimeString()

    return `
      <div style="font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px;">
        <!-- Header -->
        <div style="text-align: center; margin-bottom: 40px; border-bottom: 3px solid #6366f1; padding-bottom: 20px;">
          <div style="display: flex; align-items: center; justify-content: center; margin-bottom: 10px;">
            <div style="width: 40px; height: 40px; background: linear-gradient(135deg, #6366f1, #8b5cf6); border-radius: 8px; display: flex; align-items: center; justify-content: center; margin-right: 15px;">
              <span style="color: white; font-size: 20px; font-weight: bold;">💰</span>
            </div>
            <h1 style="margin: 0; font-size: 28px; font-weight: 800; color: #1f2937;">
              Universal Finance Calculator
            </h1>
          </div>
          <p style="margin: 5px 0; color: #6b7280; font-size: 16px;">${title}</p>
          <p style="margin: 0; color: #9ca3af; font-size: 14px;">Generated on ${currentDate} at ${currentTime}</p>
        </div>

        <!-- Results -->
        <div style="margin-bottom: 40px;">
          ${data.map(item => `
            <div style="margin-bottom: 30px; border: 2px solid #e5e7eb; border-radius: 16px; overflow: hidden;">
              <div style="background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; padding: 20px;">
                <h2 style="margin: 0; font-size: 22px; font-weight: 700;">${item.calculator}</h2>
                <p style="margin: 5px 0 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">Calculated on ${new Date(item.timestamp).toLocaleString()}</p>
              </div>
              
              <div style="padding: 20px;">
                ${item.inputs ? `
                  <div style="margin-bottom: 20px;">
                    <h3 style="margin: 0 0 10px 0; font-size: 18px; font-weight: 600; color: #374151;">📊 Inputs</h3>
                    <div style="background: #f9fafb; border-radius: 8px; padding: 15px;">
                      ${Object.entries(item.inputs).map(([key, value]) => `
                        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                          <span style="color: #6b7280; font-weight: 500;">${key.replace(/([A-Z])/g, ' $1')}:</span>
                          <span style="color: #1f2937; font-weight: 600;">${value}</span>
                        </div>
                      `).join('')}
                    </div>
                  </div>
                ` : ''}
                
                ${item.results ? `
                  <div>
                    <h3 style="margin: 0 0 10px 0; font-size: 18px; font-weight: 600; color: #374151;">💡 Results</h3>
                    <div style="background: linear-gradient(135deg, #ddd6fe, #e0e7ff); border-radius: 8px; padding: 15px; border-left: 4px solid #6366f1;">
                      ${Object.entries(item.results).map(([key, value]) => `
                        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                          <span style="color: #4c1d95; font-weight: 500;">${key.replace(/([A-Z])/g, ' $1')}:</span>
                          <span style="color: #312e81; font-weight: 700; font-size: 16px;">${value}</span>
                        </div>
                      `).join('')}
                    </div>
                  </div>
                ` : ''}
              </div>
            </div>
          `).join('')}
        </div>

        <!-- Footer -->
        <div style="text-align: center; border-top: 2px solid #e5e7eb; padding-top: 20px; color: #6b7280;">
          <p style="margin: 0; font-size: 14px;">🌟 Generated by Universal Finance Calculator</p>
          <p style="margin: 5px 0 0 0; font-size: 12px;">Professional financial planning made simple</p>
        </div>
      </div>
    `
  }

  return (
    <button
      onClick={exportToPDF}
      className="bg-gradient-to-r from-red-500 to-pink-500 hover:from-red-600 hover:to-pink-600 text-white px-6 py-3 rounded-xl font-semibold transition-all transform hover:scale-105 shadow-lg flex items-center space-x-2"
    >
      <span>📄</span>
      <span>Export to PDF</span>
    </button>
  )
}
