name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies step by step
        run: |
          echo "Installing core dependencies..."
          npm install --no-package-lock --registry https://registry.npmjs.org/ \
            vite@^5.0.0 \
            @vitejs/plugin-react@^4.2.0 \
            react@^18.2.0 \
            react-dom@^18.2.0 \
            typescript@^5.2.2

      - name: Install remaining dependencies
        run: |
          echo "Installing remaining dependencies..."
          npm install --no-package-lock --registry https://registry.npmjs.org/

      - name: Verify Vite installation
        run: |
          echo "Checking Vite installation..."
          if [ -f "./node_modules/.bin/vite" ]; then
            echo "✅ Vite binary found"
            ./node_modules/.bin/vite --version
          else
            echo "❌ Vite binary not found, trying npx..."
            npx vite@5.4.19 --version
          fi

      - name: Build project
        run: |
          if [ -f "./node_modules/.bin/vite" ]; then
            echo "Building with local Vite..."
            ./node_modules/.bin/vite build
          else
            echo "Building with npx Vite 5.4.19..."
            npx vite@5.4.19 build
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
