name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove package-lock.json temporarily
        run: rm -f package-lock.json

      - name: Install dependencies with npm install
        run: npm install --registry https://registry.npmjs.org/
        env:
          NODE_ENV: production

      - name: Verify installations
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Checking if vite is installed..."
          ls -la node_modules/.bin/ | grep vite || echo "Vite not found in .bin"
          echo "Checking vite package..."
          ls -la node_modules/vite/ || echo "Vite package not found"

      - name: Build with direct path
        run: ./node_modules/.bin/vite build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
