name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies step by step
        run: |
          echo "Installing core dependencies..."
          npm install --no-package-lock --registry https://registry.npmjs.org/ \
            vite@^5.0.0 \
            @vitejs/plugin-react@^4.2.0 \
            react@^18.2.0 \
            react-dom@^18.2.0 \
            typescript@^5.2.2

      - name: Install remaining dependencies
        run: |
          echo "Installing remaining dependencies..."
          npm install --no-package-lock --registry https://registry.npmjs.org/

      - name: Build project
        run: |
          if [ -f "./node_modules/.bin/vite" ]; then
            echo "Building with local Vite..."
            ./node_modules/.bin/vite build
          else
            echo "Building with npx Vite 5.4.19..."
            npx vite@5.4.19 build
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
